config/routes.rb
Rails.application.routes.draw do

  rutarel = (ENV['RUTA_RELATIVA'] || 'cor1440/')

  devise_scope :usuario do
    get 'sign_out' => 'devise/sessions#destroy'
    get 'salir' => 'devise/sessions#destroy',
      as: :terminar_sesion

    post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
    get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
      as: :iniciar_sesion

    # El siguiente para superar mala generación del action en el formulario
    # cuando se autentica mal (genera
    # /puntomontaje/puntomontaje/usuarios/sign_in )
    if (Rails.configuration.relative_url_root != '/')
      ruta = File.join(Rails.configuration.relative_url_root,
                       'usuarios/sign_in')
      post ruta, to: 'devise/sessions#create'
    end
  end
  devise_for :usuarios, :skip => [:registrations], module: :devise
  as :usuario do
    get 'usuarios/edit' => 'devise/registrations#edit',
      :as => 'editar_registro_usuario'
    put 'usuarios/:id' => 'devise/registrations#update',
      :as => 'registro_usuario'
  end
  resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' }

  root 'cor1440_gen/hogar#index'


  mount Msip::Engine, at: "/", as: 'msip'
  mount Cor1440Gen::Engine, at: "/", as: 'cor1440_gen'
  mount Heb412Gen::Engine, at: "/", as: 'heb412_gen'
  mount Mr519Gen::Engine, at: "/", as: 'mr519_gen'
end

app/models/ability.rb
class Ability  < Cor1440Gen::Ability

  ROLES_CA = [
    'Administrar todos los proyectos. ' +
    'Administrar todas las actividades. ' +
    'Administrar usuarios. ' + 
    'Administrar documentos en nube. ' +
    'Administrar tablas básicas. ', #ROLADMIN

    '', # 2

    'Las mismas del administradorconteos de casos. ', #ROLDIR
 
    '', # 4

    'Ver proyectos y administrar aquellos de los que es responsable. ' +
    'Administrar actividades de proyectos institucionales y en los que está en el equipo de trabajo. ' +
    'Ver documentos en nube. ', # ROLOPERADOR

    '', # 6
    '' # 7
  ]

  def tablasbasicas 
    Msip::Ability::BASICAS_PROPIAS + BASICAS_PROPIAS - [
      ['Msip', 'fuenteprensa'], 
      ['Msip', 'oficina'], 
      ['Cor1440Gen', 'proyecto'], 
      ['Msip', 'tdocumento'], 
      ['Msip', 'trelacion'], 
      ['Msip', 'tsitio']
    ]
  end

  # Autorizacion con CanCanCan
  def initialize(usuario = nil)
    initialize_cor1440_gen(usuario)
    cannot :read, Msip::Oficina
    if !usuario || usuario.fechadeshabilitacion || !usuario.rol
      return
    end
    case usuario.rol
    when Ability::ROLADMIN
      can :manage, Msip::Respaldo7z
    end

  end # initialize

end

app/models/usuario.rb
require 'cor1440_gen/concerns/models/usuario'

class Usuario < ActiveRecord::Base 
  include Cor1440Gen::Concerns::Models::Usuario

  def rol_usuario
    # No tiene restricciones de oficina
  end

end

app/controllers/application_controller.rb
class ApplicationController < Msip::ApplicationController

  # Sin definicion de autorizacion por ser utilidad
  
  protect_from_forgery with: :exception
end

app/controllers/cor1440_gen/actividades_controller.rb
require_dependency "cor1440_gen/concerns/controllers/actividades_controller"

module Cor1440Gen
  class ActividadesController < Heb412Gen::ModelosController

    include Cor1440Gen::Concerns::Controllers::ActividadesController

    before_action :set_actividad, 
      only: [:show, :edit, :update, :destroy],
      exclude: [:contar]
    load_and_authorize_resource class: Cor1440Gen::Actividad

    def edit
      edit_cor1440_gen
      @listadoasistencia = true
      render layout: 'application'
    end

  end
end

app/controllers/cor1440_gen/proyectosfinancieros_controller.rb
require_dependency "cor1440_gen/concerns/controllers/proyectosfinancieros_controller"

module Cor1440Gen
  class ProyectosfinancierosController < Heb412Gen::ModelosController
    include Cor1440Gen::Concerns::Controllers::ProyectosfinancierosController

    before_action :set_proyectofinanciero,
      only: [:show, :edit, :update, :destroy]
    skip_before_action :set_proyectofinanciero, only: [:validar]

    load_and_authorize_resource  class: Cor1440Gen::Proyectofinanciero,
      only: [:new, :create, :destroy, :edit, :update, :index, :show,
             :objetivospf]

    def atributos_index
      [ 
        :id, 
        :nombre 
      ] +
      [ :financiador_ids =>  [] ] +
      [ 
        :fechainicio_localizada,
        :fechacierre_localizada,
        :responsable,
        :proyectofinanciero_usuario,
      ] +
      [ :compromisos, 
        :monto, 
        :observaciones, 
        :objetivopf,
        :indicadorobjetivo,
        :resultadopf,
        :indicadorpf,
        :actividadpf
      ]
    end


    def atributos_show
      atributos_index - [
        :objetivopf,
        :indicadorobjetivo,
        :resultadopf,
        :indicadorpf,
        :actividadpf
      ] + [ 
        :marcologico,
        :caracterizacion, 
        :beneficiario,
        :plantillahcm,
        :anexo_proyectofinanciero
      ]
    end


  end 
end

app/controllers/usuarios_controller.rb
require 'cor1440_gen/concerns/controllers/usuarios_controller'

class UsuariosController < Msip::ModelosController
  include Cor1440Gen::Concerns::Controllers::UsuariosController

  # Sin definición de autorización por ser requerida por no autenticados
  
  def atributos_index
    [ "id",
      "nusuario",
      "nombre",
      "email",
      "grupo_ids",
      "habilitado",
    ]
  end

  def atributos_form
    r = []
    if can?(:create, ::Usuario)
      r += [ 
        "nusuario",
        "nombre",
        "descripcion"
      ]
    end
    if can?(:manage, ::Usuario)
      r += ["rol"]
    end
    if can?(:create, ::Usuario)
      r += [
        "email",
        "tema",
        "msip_grupo",
        "fechacreacion_localizada",
        "fechadeshabilitacion_localizada",
      ]
    end
    if can?(:manage, ::Usuario)
      r += [
        "idioma",
        "encrypted_password",
        "failed_attempts",
        "unlock_token",
        "locked_at"
      ]
    end
    return r
  end

  def atributos_show
    r = []
    if can?(:read, ::Usuario)
      r += [ 
        "nusuario",
        "id",
        "nombre",
        "grupos",
        "email",
      ]
    end
    if can?(:manage, ::Usuario)
      r += [
        "rol",
        "idioma",
        "encrypted_password",
        "fechacreacion_localizada",
        "fechadeshabilitacion_localizada",
        "failed_attempts",
        "unlock_token",
        "locked_at"
      ]
    end
    return r
  end
 
  def atributos_show_json
    atributos_show 
  end

  def index_reordenar(c)
    if !params || !params[:filtro] || !params[:filtro][:bushabilitado]
      c = c.where("usuario.fechadeshabilitacion IS NULL")
    end
    c = c.reorder([:nombre])
    return c
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<% content_for :title do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Proyectos" do %>
        <%= opcion_menu "Listado", cor1440_gen.proyectosfinancieros_path,
          desplegable: true %>
        <%= opcion_menu "Validar", 
          cor1440_gen.validar_proyectosfinancieros_path,
          desplegable: true %>
        <% if can? :manage, Cor1440Gen::Mindicadorpf %>
          <%= opcion_menu "Medir Indicadores", 
            cor1440_gen.mindicadorespf_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo "Actividades" do %>
        <%= opcion_menu "Listado", cor1440_gen.actividades_path,
          desplegable: true %>
        <!--%= opcion_menu "Informes", cor1440_gen.informes_path,
          desplegable: true %-->
        <%= opcion_menu "Contar por actividad de marco lógico", 
          cor1440_gen.contar_actividades_path, desplegable: true %>
        <%= opcion_menu "Contar por beneficiario y actividad de marco lógico", 
          cor1440_gen.contar_actividades_beneficiarios_path, desplegable: true %>
        <% if can? :manage, ::Msip::Orgsocial %>
          <%= opcion_menu "Organizaciones sociales", msip.orgsociales_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Msip::Persona %>
          <%= opcion_menu "Beneficiarios", msip.personas_path,
            desplegable: true %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Documentos y plantillas" do %>
        <%= opcion_menu "Manual de Cor1440", 
          'https://docs.google.com/document/d/1mmydkqNmZbXkzcpkiegQ_XAP_NkjfX-RXgcW1yzjdpE/edit?usp=sharing', 
          target: '_blank', desplegable: true %>
        <%= opcion_menu "Nube", heb412_gen.sisini_path, 
          desplegable: true %>
        <% if can? :manage, ::Heb412Gen::Plantillahcm %>
          <%= opcion_menu "Plantillas para listados en hojas de calculo",
            heb412_gen.plantillashcm_path,
          desplegable: true %>
        <% end %>
        <% if can? :manage, ::Heb412Gen::Plantillahcr %>
          <%= opcion_menu "Plantillas para un registro en hoja de calculo",
            heb412_gen.plantillashcr_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave y tema", main_app.editar_registro_usuario_path,
            desplegable: true %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu "Usuarios", main_app.usuarios_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu "Formularios", mr519_gen.formularios_path,
            desplegable: true %>
        <% end %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu "Tablas básicas", msip.tablasbasicas_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Msip::Respaldo7z %>
          <%= opcion_menu "Respaldo cifrado", msip.respaldo7z_path,
            desplegable: true %>
        <% end %>
        <%= opcion_menu "Ver Control de Acceso", 
          msip.ayuda_controldeacceso_path, desplegable: true %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu "Acerca de", msip.acercade_path, desplegable: true %>
      <%= opcion_menu "Iniciar Sesión", main_app.iniciar_sesion_path,
        desplegable: true %>
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p>Datos de CODACOP<br>
  <span class='derechos'>Sistema de información con fuentes de 
    <a href='https://github.com/pasosdeJesus/si_codacop'>código abierto</a>.
    <br/>
    Desarrollado por <a id='pasosdeJesus' href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 2023. 
  </span></p>
<% end %>

<%= render template: "layouts/msip/application" %>